name: deep_link_navigation_example
description: Deep link navigation for Flutter apps with an elegant configuation internally orchestrating a native Flutter navigator.
version: 1.0.0
author: Dennis Krasnov <dennis@krasnov.dev>
homepage: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation
repository: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation
issue_tracker: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation/issues

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  deep_link_navigation:
    path: ../