name: deep_link_navigation
description: Deep link navigation for Flutter apps with elegant configuation orchestrating a native flutter navigator.
version: 0.1.2
author: Dennis Krasnov <dennis@krasnov.dev>
homepage: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation
repository: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation
issue_tracker: https://github.com/Dennis-Krasnov/Flutter-Deep-Link-Navigation/issues

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0
  after_layout: ^1.0.7+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

