name: deep_link_navigation
description: ...
version: 0.1.0
author: Dennis Krasnov <dennis@krasnov.dev>
homepage: ...
#repository: https://github.com/felangel/bloc
#issue_tracker: https://github.com/felangel/bloc/issues
#homepage: https://bloclibrary.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

