name: single_base_route
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  deep_link_navigation:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_driver:
    sdk: flutter

  test: any
  flutter_gherkin: ^1.1.4

flutter:
  uses-material-design: true